#!/bin/bash  

# Only start database if NO_DB is not passed
if [ -z ${NO_DB+x} ]; then
	echo "Starting MySQL..."
	/etc/init.d/mysql start
else
	echo "Running without DB..."
fi

echo "Starting Apache..."
apache2ctl start

echo "Showing logs..."
tail -f /var/log/apache2/*.log
